name: CI/CD 

on:
  push:
    branches:
        - master
  pull_request:
    branches:
        - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        name: Use Node.js
      - uses: actions/setup-node@v4
        with: 
            node-version: '21.4.0'
            cache: 'npm'
            cache-dependency-path: './server/package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm run test

