name: Build and Deploy

on:
  push:
    branches:
        - master
  pull_request:
    branches:
        - master

env:
  MONGODB_URI: mongodb+srv://root:root@atlascluster.r3jgorq.mongodb.net
  MONGO_DB_NAME: rugged2
  MONGO_DB_TEST: test
  ACCESS_TOKEN_SECRET: sfnjkasfjklas
  REFRESH_TOKEN_SECRET: fnioenlksdnk

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Run test
        working-directory: ./server
        run: npm run test

